spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.113.186.41:3306/chapter05?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource